language: generic
sudo : required
services:
    - docker
before_install: 
    - docker build -t mnrohit/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true mnrohit/docker-react npm run test -- --coverage
deploy: 
    provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    region: "us-east-2"
    app: "Docker-Frontend-Web-React"
    env: "DockerFrontendWebReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-449009575516"
    bucket_path: "Docker-Frontend-Web-React"
    on: 
        branch: master

